name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          username: hexsix
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: hexsix/mastodon
          tags: latest
